### ISSUE TITLE
[Feature Request]: Add an individual close button on each tab like in Chrome

### ISSUE THREAD

**Issue by PPPDUD** [michaeleldar/Cobalt#2]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you would like!

The title says it all.

### Describe alternatives you have considered.

Uhh.. no.

**Comment by michaeleldar** [comment]
Yeah... I tried to do this before and it completely failed.

Also this is supposed to be very similar to catalyst so I probably won’t add it... unless you make a working pull request...
